"""Job Runs API"""

from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from pydantic import BaseModel
from typing import List, Optional
from datetime import datetime
from uuid import UUID

from database import get_db
from services.auth import get_current_user
import models

router = APIRouter()


class JobRunResponse(BaseModel):
    id: UUID
    report_version_id: UUID
    triggered_by: str
    status: str
    started_at: Optional[datetime]
    ended_at: Optional[datetime]
    error_message: Optional[str]
    created_at: datetime

    class Config:
        from_attributes = True


@router.get("", response_model=List[JobRunResponse])
async def list_runs(
    skip: int = 0,
    limit: int = 100,
    status: Optional[str] = None,
    current_user: models.User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """List job runs for the current tenant"""
    query = db.query(models.JobRun).filter(
        models.JobRun.tenant_id == current_user.tenant_id
    ).order_by(models.JobRun.created_at.desc())
    
    if status:
        query = query.filter(models.JobRun.status == status)
    
    runs = query.offset(skip).limit(limit).all()
    return runs


@router.get("/{run_id}", response_model=JobRunResponse)
async def get_run(
    run_id: UUID,
    current_user: models.User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """Get details of a specific job run"""
    run = db.query(models.JobRun).filter(
        models.JobRun.id == run_id,
        models.JobRun.tenant_id == current_user.tenant_id
    ).first()
    
    if not run:
        raise HTTPException(status_code=404, detail="Job run not found")
    
    return run


@router.get("/{run_id}/logs")
async def get_run_logs(
    run_id: UUID,
    current_user: models.User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """Get logs for a job run - TODO: Stream from MinIO"""
    run = db.query(models.JobRun).filter(
        models.JobRun.id == run_id,
        models.JobRun.tenant_id == current_user.tenant_id
    ).first()
    
    if not run:
        raise HTTPException(status_code=404, detail="Job run not found")
    
    # TODO: Fetch actual logs from MinIO using run.logs_uri
    return {"logs": "Log streaming not yet implemented - TODO for v1"}


@router.get("/{run_id}/artifacts")
async def list_run_artifacts(
    run_id: UUID,
    current_user: models.User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """List artifacts generated by a job run"""
    run = db.query(models.JobRun).filter(
        models.JobRun.id == run_id,
        models.JobRun.tenant_id == current_user.tenant_id
    ).first()
    
    if not run:
        raise HTTPException(status_code=404, detail="Job run not found")
    
    return run.artifacts


# TODO: Implement
# - GET /{run_id}/artifacts/{artifact_id}/download - Download artifact
# POST /{run_id}/rerun - Rerun job
